# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20170219_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='accept_appointment_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bonding', 'Bonding'), ('Braces', 'Braces'), ('Bridges', 'Bridges'), ('Implants', 'Implants'), ('Crowns', 'Crowns'), ('Caps', 'Caps'), ('Dentures', 'Dentures'), ('Extractions', 'Extractions'), ('Gum Surgery', 'Gum Surgery'), ('Oral Cancer Examination', 'Oral Cancer Examination'), ('Root Canal', 'Root Canal'), ('Teeth Whitening', 'Teeth Whitening'), ('Veneers', 'Veneers')], default='Teeth Whitening', max_length=135),
        ),
        migrations.AlterField(
            model_name='facility',
            name='accept_dental_plans',
            field=models.TextField(default='Aetna'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.TextField(default='123 Example Ln\nSpringfield, IL\n55555'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='5555555555', max_length=128),
        ),
        migrations.AlterField(
            model_name='facility',
            name='public_email',
            field=models.EmailField(default='JaneDoe@example.com', max_length=254),
        ),
    ]
