# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 01:18
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20170219_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='accept_appointment_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bonding', 'Bonding'), ('Braces', 'Braces'), ('Bridges', 'Bridges'), ('Implants', 'Implants'), ('Crowns', 'Crowns'), ('Caps', 'Caps'), ('Dentures', 'Dentures'), ('Extractions', 'Extractions'), ('Gum Surgery', 'Gum Surgery'), ('Oral Cancer Examination', 'Oral Cancer Examination'), ('Root Canal', 'Root Canal'), ('Teeth Whitening', 'Teeth Whitening'), ('Veneers', 'Veneers')], default=['Teeth Whitening'], max_length=135),
        ),
        migrations.AlterField(
            model_name='facility',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=128),
        ),
    ]
